In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("SALES ANALYSIS")

print("Shape of data",sales_data.shape)

print("Data for three ",sales_data[3])
print("Data for first three ",sales_data[:3])

# First colon is that all data second colon is range of the data so from 1 index to all index 
print("Data in particular range ",sales_data[:,1:])
print("Data in particular range ",sales_data[1:,2:4])

SALES ANALYSIS
Shape of data (5, 5)
Data for three  [     4 180000 210000 240000 270000]
Data for first three  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Data in particular range  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
Data in particular range  [[140000 160000]
 [230000 260000]
 [210000 240000]
 [185000 205000]]


In [5]:
# Total Sales per Year


print(np.sum(sales_data,axis=0))

yearly_total = np.sum(sales_data[:, 1:],axis=0)
print("Yearly Total without index",yearly_total)
total_each_sum = np.sum(sales_data[:, 1:],axis=1)
print("Total Each Sum",total_each_sum)

[     15  810000  945000 1085000 1240000]
Yearly Total without index [ 810000  945000 1085000 1240000]
Total Each Sum [800000 610000 990000 900000 780000]


# Minimum Sales per restaurant


In [11]:
min_sales = np.min(sales_data[:, 1:],axis=1)
print(min_sales)

# Maximim Sales per year for all restaurant
max_sales = np.max(sales_data[:, 1:],axis=0)
print(max_sales)

# Average Sales per restaurant
avg_sales = np.mean(sales_data[:, 1:],axis=1)
print(avg_sales)

[150000 120000 200000 180000 160000]
[200000 230000 260000 300000]
[200000. 152500. 247500. 225000. 195000.]


In [27]:
cumsum = np.cumsum(sales_data[:, 1:],axis=1)
print(cumsum)

plt.figure(figsize=(10,6))
plt.plot(np.mean(cumsum,axis=0))
plt.title("Avg Cumulative sale across all restaurant")
plt.xlabel("Years")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

In [21]:
vector1 = np.array([1,2,3,4,5])
vector2 = np.array([6,7,8,9,10])

print("Vector Addition", vector1 + vector2)
print("Vector Multiplication", vector1 * vector2)
print("Dot Product", np.dot(vector1 , vector2))

angle = np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1) * np.linalg.norm(vector2)))
print("Angle",angle)

Vector Addition [ 7  9 11 13 15]
Vector Multiplication [ 6 14 24 36 50]
Dot Product 130
Angle 0.26554161733900966


In [23]:
restaurant_types = np.array(["chinese","pizza","burger","cafe"])
# vectorize lets us attach any regular python operation
vectorize_upper = np.vectorize(str.upper)
print(vectorize_upper(restaurant_types))

['CHINESE' 'PIZZA' 'BURGER' 'CAFE']


In [26]:
monthly_avg = sales_data[:, 1:] /12
print(sales_data)
print(monthly_avg)

[[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]
 [     4 180000 210000 240000 270000]
 [     5 160000 185000 205000 230000]]
[[12500.         15000.         18333.33333333 20833.33333333]
 [10000.         11666.66666667 13333.33333333 15833.33333333]
 [16666.66666667 19166.66666667 21666.66666667 25000.        ]
 [15000.         17500.         20000.         22500.        ]
 [13333.33333333 15416.66666667 17083.33333333 19166.66666667]]
