## Numpy array and Basics

In [1]:
import numpy as np

## Creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### List VS Numpy Array

In [ ]:
py_list = [1,2,3]
print("Python List Multiplication ", py_list*2)

np_array = np.array([1,2,3]) # element wise multiplication
print("Python List Multiplication ", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("List Operation: ", time.time()-start)
start = time.time()
np_array = np.arange(10000000) * 2
print("Numpy Operation: ", time.time()-start)

Python List Multiplication  [1, 2, 3, 1, 2, 3]
Python List Multiplication  [2 4 6]
List Operation:  0.337352991104126
Numpy Operation:  0.025873899459838867


### Creating Array from scratch

In [17]:
zeros = np.zeros((3,4))
print(zeros)

ones = np.ones((2,3))
print(ones)

full = np.full((2,2), 7)
print(full)

random = np.random.random((2,3))
print(random)

# Start , end non inclusive and step
sequence = np.arange(0,10,2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.02843676 0.65885094 0.93362298]
 [0.6175702  0.43533421 0.44992039]]
[0 2 4 6 8]


### Vector, Matrix and Tensor

In [22]:
vector = np.array([1,2,3])
print("Vector : ",vector)
matrix = np.array([[1,2,3],[4,5,6]])
print("Matrix : ",matrix)
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("Tensor : ",tensor)

Vector :  [1 2 3]
Matrix :  [[1 2 3]
 [4 5 6]]
Tensor :  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
