## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

print("Basic Slicing",arr[2:7])
print("With Step",arr[1:8:2])
print("Negative Indexing",arr[-3])

[ 1  2  3  4  5  6  7  8  9 10]
Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

#print("Specific Elem",arr_2d[1][2])
print("Specific Elem",arr_2d[1,2])
print("Specific Row",arr_2d[1])
print("Specific Col",arr_2d[:,1])

Specific Elem 6
Specific Row [4 5 6]
Specific Col [2 5 8]


# Sorting

In [5]:
unsorted = np.array([9,3,4,2,5,6,4,2,36,67,34])
print("Sorted Array",np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Original",arr_2d_unsorted)
print("Sorted 2D Array by Col", np.sort(arr_2d_unsorted,axis=0))
print("Sorted 2D Array by Row", np.sort(arr_2d_unsorted,axis=1))

Sorted Array [ 2  2  3  4  4  5  6  9 34 36 67]
Original [[3 1]
 [1 2]
 [2 3]]
Sorted 2D Array by Col [[1 1]
 [2 2]
 [3 3]]
Sorted 2D Array by Row [[1 3]
 [1 2]
 [2 3]]


## Filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers",even_numbers)

Even Numbers [ 2  4  6  8 10]


## Filter with mask

In [7]:
mask = numbers > 5
print("Mask",mask)
print("Number Greater Thann 5",numbers[mask])

Mask [False False False False False  True  True  True  True  True]
Number Greater Thann 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print("Where Result",where_result)
print("Where Result is greater than 5",numbers[where_result])

[1 3 5]
Where Result (array([5, 6, 7, 8, 9]),)
Where Result is greater than 5 [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers>5)
print(condition_array)
condition_array = np.where(numbers>5,numbers*2,numbers)
print(condition_array)
condition_array = np.where(numbers>5,numbers*1,numbers)
print(condition_array)
condition_array = np.where(numbers>5,numbers,numbers)
print(condition_array)


# First is condtion that where number is greater than 5 then second so multiply the number * 2 that are greater than 5

# It like a ternary operator like we did a>b ? a : b 

condition_array = np.where(numbers>5,"true","false")
print(condition_array)
print(numbers)


(array([5, 6, 7, 8, 9]),)
[ 1  2  3  4  5 12 14 16 18 20]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']
[ 1  2  3  4  5  6  7  8  9 10]


## Adding and Removing Data

In [15]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

added = arr1+arr2
print(added)
combined = np.concatenate((arr1,arr2))
print(combined)
# combined_concat = np.concat((arr1,arr2))  # In numpy there is no caocat here is working due to another library has patched NumPy or is shadowing it but in Numpy directly no concat is present
# print(combined_concat)

[5 7 9]
[1 2 3 4 5 6]


### Array Compatibility

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,10])

print("Compatibility Shape a and b", a.shape==b.shape)
print("Compatibility Shape a and c", a.shape==c.shape)



Compatibility Shape a and b True
Compatibility Shape a and c False


In [24]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
#vstack adds new row
with_new_row = np.vstack((original,new_row))

print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [30]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr,2) # Gives array after deletion
print(deleted)
deleted2 = np.delete(arr, [1, 2]) # Gives array after deletion
print(deleted2)

[1 2 4 5]
[1 4 5]
