In [2]:
import numpy as np
import matplotlib.pyplot as plt

Matplotlib is building the font cache; this may take a moment.


In [15]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("SALES ANALYSIS")

print("Shape of data",sales_data.shape)

print("Data for three ",sales_data[3])
print("Data for first three ",sales_data[:3])

# First colon is that all data second colon is range of the data so from 1 index to all index 
print("Data in particular range ",sales_data[:,1:])
print("Data in particular range ",sales_data[1:,2:4])

SALES ANALYSIS
Shape of data (5, 5)
Data for three  [     4 180000 210000 240000 270000]
Data for first three  [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
Data in particular range  [[150000 180000 220000 250000]
 [120000 140000 160000 190000]
 [200000 230000 260000 300000]
 [180000 210000 240000 270000]
 [160000 185000 205000 230000]]
Data in particular range  [[140000 160000]
 [230000 260000]
 [210000 240000]
 [185000 205000]]


In [21]:
# Total Sales per Year


print(np.sum(sales_data,axis=0))

yearly_total = np.sum(sales_data[:, 1:],axis=0)
print("Yearly Total without index",yearly_total)
total_each_sum = np.sum(sales_data[:, 1:],axis=1)
print("Total Each Sum",total_each_sum)

[     15  810000  945000 1085000 1240000]
Yearly Total without index [ 810000  945000 1085000 1240000]
Total Each Sum [800000 610000 990000 900000 780000]
